#version 450

layout(set = 0, binding = 0, r32f) uniform image2D sampledTexture0;
layout(set = 1, binding = 0, r32f) uniform image2D sampledTexture1;
layout(set = 2, binding = 0, r32f) uniform image2D sampledTexture2;

layout (local_size_x = 16) in;
layout (local_size_y = 16) in;

void main() 
{
   imageStore(sampledTexture0, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), vec4(0.5f, 0.0f, 0.0f, 0.0f));
}
